<?php
 	function removeStopWords($titleString, $stopWords) {
	    $numbers = array("1", "2", "3", "4", "5", "6", "7", "8", "9", "0");
	    $puntation = array(".", ",", ":", ";", "-", "_", "?", "!", "%", "&", "(", ")", "@", "#");
		
        $titleString = str_replace($numbers, "", $titleString);
        $titleString = str_replace($puntation, "", $titleString);
		$titleWords = \explode(" ", $titleString);
		$result = array();
		foreach ($titleWords as $word) {
			$isStopWord = \in_array(\strtolower($word), $stopWords);
			if (!$isStopWord) {
				$result[] = $word;
			}
		}
		return \join(' ', $result);
	}
 	
 	function cleanStopWords(&$stopWords) {
 		foreach ($stopWords as $key => $stopWord) {
 			$stopWords[$key] = \trim($stopWord, "\n");
 			$stopWords[$key] = \trim($stopWord);
 		}
 	}
 	
 	function rulesInterpreter($phrase){
		
		//Array dei termini da sostituire
		$toReplace = array("age", "category", "difficulty", "format", "language", "resourcetype", "status", "time",
        "s_acq_skill_probabilityandstatistics_probability =", "s_acq_skill_probabilityandstatistics_statistics =", "s_acq_skill_probabilityandstatistics_regression =", "s_acq_skill_probabilityandstatistics_computationalstatistics =", "s_acq_skill_probabilityandstatistics_randomprocess =", "s_acq_skill_probabilityandstatistics_mathematicalstatistics =", "s_acq_skill_probabilityandstatistics_multivariatestatistics =", "s_acq_skill_probabilityandstatistics_dataanalysis =", "s_acq_skill_probabilityandstatistics_quantumstatistics =", "s_acq_skill_probabilityandstatistics_appliedfield =",
        "s_req_skill_probabilityandstatistics_probability =", "s_req_skill_probabilityandstatistics_statistics =", "s_req_skill_probabilityandstatistics_regression =", "s_req_skill_probabilityandstatistics_computationalstatistics =", "s_req_skill_probabilityandstatistics_randomprocess =", "s_req_skill_probabilityandstatistics_mathematicalstatistics =", "s_req_skill_probabilityandstatistics_multivariatestatistics =", "s_req_skill_probabilityandstatistics_dataanalysis =", "s_req_skill_probabilityandstatistics_quantumstatistics =", "s_req_skill_probabilityandstatistics_appliedfield =",
        "d_acq_skill_probabilityandstatistics_probability =", "d_acq_skill_probabilityandstatistics_statistics =", "d_acq_skill_probabilityandstatistics_regression =", "d_acq_skill_probabilityandstatistics_computationalstatistics =", "d_acq_skill_probabilityandstatistics_randomprocess =", "d_acq_skill_probabilityandstatistics_mathematicalstatistics =", "d_acq_skill_probabilityandstatistics_multivariatestatistics =", "d_acq_skill_probabilityandstatistics_dataanalysis =", "d_acq_skill_probabilityandstatistics_quantumstatistics =", "d_acq_skill_probabilityandstatistics_appliedfield =",
        "d_req_skill_probabilityandstatistics_probability =", "d_req_skill_probabilityandstatistics_statistics =", "d_req_skill_probabilityandstatistics_regression =", "d_req_skill_probabilityandstatistics_computationalstatistics =", "d_req_skill_probabilityandstatistics_randomprocess =", "d_req_skill_probabilityandstatistics_mathematicalstatistics =", "d_req_skill_probabilityandstatistics_multivariatestatistics =", "d_req_skill_probabilityandstatistics_dataanalysis =", "d_req_skill_probabilityandstatistics_quantumstatistics  =", "d_req_skill_probabilityandstatistics_appliedfield =",
        "Age_young", "Age_teenager", "Age_mature", "Age_university", "Age_phd", "Age_adult", "Age_young-teenager", "Age_young-mature", "Age_young-university", "Age_young-phd", "Age_young-adult", "Age_teenager-mature", "Age_teenager-university", "Age_teenager-phd", "Age_teenager-adult", "Age_mature-university", "Age_mature-phd", "Age_mature-adult", "Age_university-phd", "Age_university-adult", "Age_phd-adult",
        "category_probabilityandstatistics",
        "Difficulty_veryeasy", "Difficulty_easy", "Difficulty_medium", "Difficulty_difficult", "Difficulty_verydifficult",
        "language_english", "language_italian", "language_bulgarian", "language_turkish",
        "resourcetype_exercise", "resourcetype_simulation", "resourcetype_questionnaire", "resourcetype_diagram", "resourcetype_figure", "resourcetype_graph", "resourcetype_index", "resourcetype_slide", "resourcetype_table", "resourcetype_narrativetext", "resourcetype_exam", "resourcetype_experiment", "resourcetype_problemstatement", "resourcetype_selfassessment", "resourcetype_lecture",
        "status_white", "status_green", "status_yellow", "status_red", "status_black", "status_gold",
        "time_minutes30", "time_minutes60", "time_minutes90", "time_minutes120p",
        "s_acq_skill_probabilityandstatistics_probability_absent", "s_acq_skill_probabilityandstatistics_probability_low", "s_acq_skill_probabilityandstatistics_probability_medium-low", "s_acq_skill_probabilityandstatistics_probability_medium", "s_acq_skill_probabilityandstatistics_probability_medium-high", "s_acq_skill_probabilityandstatistics_probability_high",
        "s_acq_skill_probabilityandstatistics_statistics_absent", "s_acq_skill_probabilityandstatistics_statistics_low", "s_acq_skill_probabilityandstatistics_statistics_medium-low", "s_acq_skill_probabilityandstatistics_statistics_medium", "s_acq_skill_probabilityandstatistics_statistics_medium-high", "s_acq_skill_probabilityandstatistics_statistics_high",
        "s_acq_skill_probabilityandstatistics_regression_absent", "s_acq_skill_probabilityandstatistics_regression_low", "s_acq_skill_probabilityandstatistics_regression_medium-low", "s_acq_skill_probabilityandstatistics_regression_medium", "s_acq_skill_probabilityandstatistics_regression_medium-high", "s_acq_skill_probabilityandstatistics_regression_high",
        "s_acq_skill_probabilityandstatistics_computationalstatistics_absent", "s_acq_skill_probabilityandstatistics_computationalstatistics_low", "s_acq_skill_probabilityandstatistics_computationalstatistics_medium-low", "s_acq_skill_probabilityandstatistics_computationalstatistics_medium", "s_acq_skill_probabilityandstatistics_computationalstatistics_medium-high", "s_acq_skill_probabilityandstatistics_computationalstatistics_high",
        "s_acq_skill_probabilityandstatistics_randomprocess_absent", "s_acq_skill_probabilityandstatistics_randomprocess_low", "s_acq_skill_probabilityandstatistics_randomprocess_medium-low", "s_acq_skill_probabilityandstatistics_randomprocess_medium", "s_acq_skill_probabilityandstatistics_randomprocess_medium-high", "s_acq_skill_probabilityandstatistics_randomprocess_high",
        "s_acq_skill_probabilityandstatistics_mathematicalstatistics_absent", "s_acq_skill_probabilityandstatistics_mathematicalstatistics_low", "s_acq_skill_probabilityandstatistics_mathematicalstatistics_medium-low", "s_acq_skill_probabilityandstatistics_mathematicalstatistics_medium", "s_acq_skill_probabilityandstatistics_mathematicalstatistics_medium-high", "s_acq_skill_probabilityandstatistics_mathematicalstatistics_high",
        "s_acq_skill_probabilityandstatistics_multivariatestatistics_absent", "s_acq_skill_probabilityandstatistics_multivariatestatistics_low", "s_acq_skill_probabilityandstatistics_multivariatestatistics_medium-low", "s_acq_skill_probabilityandstatistics_multivariatestatistics_medium", "s_acq_skill_probabilityandstatistics_multivariatestatistics_medium-high", "s_acq_skill_probabilityandstatistics_multivariatestatistics_high",
        "s_acq_skill_probabilityandstatistics_dataanalysis_absent", "s_acq_skill_probabilityandstatistics_dataanalysis_low", "s_acq_skill_probabilityandstatistics_dataanalysis_medium-low", "s_acq_skill_probabilityandstatistics_dataanalysis_medium", "s_acq_skill_probabilityandstatistics_dataanalysis_medium-high", "s_acq_skill_probabilityandstatistics_dataanalysis_high",
        "s_acq_skill_probabilityandstatistics_quantumstatistics_absent", "s_acq_skill_probabilityandstatistics_quantumstatistics_low", "s_acq_skill_probabilityandstatistics_quantumstatistics_medium-low", "s_acq_skill_probabilityandstatistics_quantumstatistics_medium", "s_acq_skill_probabilityandstatistics_quantumstatistics_medium-high", "s_acq_skill_probabilityandstatistics_quantumstatistics_high",
        "s_acq_skill_probabilityandstatistics_appliedfield_absent", "s_acq_skill_probabilityandstatistics_appliedfield_low", "s_acq_skill_probabilityandstatistics_appliedfield_medium-low", "s_acq_skill_probabilityandstatistics_appliedfield_medium", "s_acq_skill_probabilityandstatistics_appliedfield_medium-high", "s_acq_skill_probabilityandstatistics_appliedfield_high",
        "s_req_skill_probabilityandstatistics_probability_absent", "s_req_skill_probabilityandstatistics_probability_low", "s_req_skill_probabilityandstatistics_probability_medium-low", "s_req_skill_probabilityandstatistics_probability_medium", "s_req_skill_probabilityandstatistics_probability_medium-high", "s_req_skill_probabilityandstatistics_probability_high",
        "s_req_skill_probabilityandstatistics_statistics_absent", "s_req_skill_probabilityandstatistics_statistics_low", "s_req_skill_probabilityandstatistics_statistics_medium-low", "s_req_skill_probabilityandstatistics_statistics_medium", "s_req_skill_probabilityandstatistics_statistics_medium-high", "s_req_skill_probabilityandstatistics_statistics_high",
        "s_req_skill_probabilityandstatistics_regression_absent", "s_req_skill_probabilityandstatistics_regression_low", "s_req_skill_probabilityandstatistics_regression_medium-low", "s_req_skill_probabilityandstatistics_regression_medium", "s_req_skill_probabilityandstatistics_regression_medium-high", "s_req_skill_probabilityandstatistics_regression_high",
        "s_req_skill_probabilityandstatistics_computationalstatistics_absent", "s_req_skill_probabilityandstatistics_computationalstatistics_low", "s_req_skill_probabilityandstatistics_computationalstatistics_medium-low", "s_req_skill_probabilityandstatistics_computationalstatistics_medium", "s_req_skill_probabilityandstatistics_computationalstatistics_medium-high", "s_req_skill_probabilityandstatistics_computationalstatistics_high",
        "s_req_skill_probabilityandstatistics_randomprocess_absent", "s_req_skill_probabilityandstatistics_randomprocess_low", "s_req_skill_probabilityandstatistics_randomprocess_medium-low", "s_req_skill_probabilityandstatistics_randomprocess_medium", "s_req_skill_probabilityandstatistics_randomprocess_medium-high", "s_req_skill_probabilityandstatistics_randomprocess_high",
        "s_req_skill_probabilityandstatistics_mathematicalstatistics_absent", "s_req_skill_probabilityandstatistics_mathematicalstatistics_low", "s_req_skill_probabilityandstatistics_mathematicalstatistics_medium-low", "s_req_skill_probabilityandstatistics_mathematicalstatistics_medium", "s_req_skill_probabilityandstatistics_mathematicalstatistics_medium-high", "s_req_skill_probabilityandstatistics_mathematicalstatistics_high",
        "s_req_skill_probabilityandstatistics_multivariatestatistics_absent", "s_req_skill_probabilityandstatistics_multivariatestatistics_low", "s_req_skill_probabilityandstatistics_multivariatestatistics_medium-low", "s_req_skill_probabilityandstatistics_multivariatestatistics_medium", "s_req_skill_probabilityandstatistics_multivariatestatistics_medium-high", "s_req_skill_probabilityandstatistics_multivariatestatistics_high",
        "s_req_skill_probabilityandstatistics_dataanalysis_absent", "s_req_skill_probabilityandstatistics_dataanalysis_low", "s_req_skill_probabilityandstatistics_dataanalysis_medium-low", "s_req_skill_probabilityandstatistics_dataanalysis_medium", "s_req_skill_probabilityandstatistics_dataanalysis_medium-high", "s_req_skill_probabilityandstatistics_dataanalysis_high",
        "s_req_skill_probabilityandstatistics_quantumstatistics_absent", "s_req_skill_probabilityandstatistics_quantumstatistics_low", "s_req_skill_probabilityandstatistics_quantumstatistics_medium-low", "s_req_skill_probabilityandstatistics_quantumstatistics_medium", "s_req_skill_probabilityandstatistics_quantumstatistics_medium-high", "s_req_skill_probabilityandstatistics_quantumstatistics_high",
        "s_req_skill_probabilityandstatistics_appliedfield_absent", "s_req_skill_probabilityandstatistics_appliedfield_low", "s_req_skill_probabilityandstatistics_appliedfield_medium-low", "s_req_skill_probabilityandstatistics_appliedfield_medium", "s_req_skill_probabilityandstatistics_appliedfield_medium-high", "s_req_skill_probabilityandstatistics_appliedfield_high",
        "d_acq_skill_probabilityandstatistics_probability_absent", "d_acq_skill_probabilityandstatistics_probability_low", "d_acq_skill_probabilityandstatistics_probability_medium-low", "d_acq_skill_probabilityandstatistics_probability_medium", "d_acq_skill_probabilityandstatistics_probability_medium-high", "d_acq_skill_probabilityandstatistics_probability_high",
        "d_acq_skill_probabilityandstatistics_statistics_absent", "d_acq_skill_probabilityandstatistics_statistics_low", "d_acq_skill_probabilityandstatistics_statistics_medium-low", "d_acq_skill_probabilityandstatistics_statistics_medium", "d_acq_skill_probabilityandstatistics_statistics_medium-high", "d_acq_skill_probabilityandstatistics_statistics_high",
        "d_acq_skill_probabilityandstatistics_regression_absent", "d_acq_skill_probabilityandstatistics_regression_low", "d_acq_skill_probabilityandstatistics_regression_medium-low", "d_acq_skill_probabilityandstatistics_regression_medium", "d_acq_skill_probabilityandstatistics_regression_medium-high", "d_acq_skill_probabilityandstatistics_regression_high",
        "d_acq_skill_probabilityandstatistics_computationalstatistics_absent", "d_acq_skill_probabilityandstatistics_computationalstatistics_low", "d_acq_skill_probabilityandstatistics_computationalstatistics_medium-low", "d_acq_skill_probabilityandstatistics_computationalstatistics_medium", "d_acq_skill_probabilityandstatistics_computationalstatistics_medium-high", "d_acq_skill_probabilityandstatistics_computationalstatistics_high",
        "d_acq_skill_probabilityandstatistics_randomprocess_absent", "d_acq_skill_probabilityandstatistics_randomprocess_low", "d_acq_skill_probabilityandstatistics_randomprocess_medium-low", "d_acq_skill_probabilityandstatistics_randomprocess_medium", "d_acq_skill_probabilityandstatistics_randomprocess_medium-high", "d_acq_skill_probabilityandstatistics_randomprocess_high",
        "d_acq_skill_probabilityandstatistics_mathematicalstatistics_absent", "d_acq_skill_probabilityandstatistics_mathematicalstatistics_low", "d_acq_skill_probabilityandstatistics_mathematicalstatistics_medium-low", "d_acq_skill_probabilityandstatistics_mathematicalstatistics_medium", "d_acq_skill_probabilityandstatistics_mathematicalstatistics_medium-high", "d_acq_skill_probabilityandstatistics_mathematicalstatistics_high",
        "d_acq_skill_probabilityandstatistics_multivariatestatistics_absent", "d_acq_skill_probabilityandstatistics_multivariatestatistics_low", "d_acq_skill_probabilityandstatistics_multivariatestatistics_medium-low", "d_acq_skill_probabilityandstatistics_multivariatestatistics_medium", "d_acq_skill_probabilityandstatistics_multivariatestatistics_medium-high", "d_acq_skill_probabilityandstatistics_multivariatestatistics_high",
        "d_acq_skill_probabilityandstatistics_dataanalysis_absent", "d_acq_skill_probabilityandstatistics_dataanalysis_low", "d_acq_skill_probabilityandstatistics_dataanalysis_medium-low", "d_acq_skill_probabilityandstatistics_dataanalysis_medium", "d_acq_skill_probabilityandstatistics_dataanalysis_medium-high", "d_acq_skill_probabilityandstatistics_dataanalysis_high",
        "d_acq_skill_probabilityandstatistics_quantumstatistics_absent", "d_acq_skill_probabilityandstatistics_quantumstatistics_low", "d_acq_skill_probabilityandstatistics_quantumstatistics_medium-low", "d_acq_skill_probabilityandstatistics_quantumstatistics_medium", "d_acq_skill_probabilityandstatistics_quantumstatistics_medium-high", "d_acq_skill_probabilityandstatistics_quantumstatistics_high",
        "d_acq_skill_probabilityandstatistics_appliedfield_absent", "d_acq_skill_probabilityandstatistics_appliedfield_low", "d_acq_skill_probabilityandstatistics_appliedfield_medium-low", "d_acq_skill_probabilityandstatistics_appliedfield_medium", "d_acq_skill_probabilityandstatistics_appliedfield_medium-high", "d_acq_skill_probabilityandstatistics_appliedfield_high",
        "d_req_skill_probabilityandstatistics_probability_absent", "d_req_skill_probabilityandstatistics_probability_low", "d_req_skill_probabilityandstatistics_probability_medium-low", "d_req_skill_probabilityandstatistics_probability_medium", "d_req_skill_probabilityandstatistics_probability_medium-high", "d_req_skill_probabilityandstatistics_probability_high",
        "d_req_skill_probabilityandstatistics_statistics_absent", "d_req_skill_probabilityandstatistics_statistics_low", "d_req_skill_probabilityandstatistics_statistics_medium-low", "d_req_skill_probabilityandstatistics_statistics_medium", "d_req_skill_probabilityandstatistics_statistics_medium-high", "d_req_skill_probabilityandstatistics_statistics_high",
        "d_req_skill_probabilityandstatistics_regression_absent", "d_req_skill_probabilityandstatistics_regression_low", "d_req_skill_probabilityandstatistics_regression_medium-low", "d_req_skill_probabilityandstatistics_regression_medium", "d_req_skill_probabilityandstatistics_regression_medium-high", "d_req_skill_probabilityandstatistics_regression_high",
        "d_req_skill_probabilityandstatistics_computationalstatistics_absent", "d_req_skill_probabilityandstatistics_computationalstatistics_low", "d_req_skill_probabilityandstatistics_computationalstatistics_medium-low", "d_req_skill_probabilityandstatistics_computationalstatistics_medium", "d_req_skill_probabilityandstatistics_computationalstatistics_medium-high", "d_req_skill_probabilityandstatistics_computationalstatistics_high",
        "d_req_skill_probabilityandstatistics_randomprocess_absent", "d_req_skill_probabilityandstatistics_randomprocess_low", "d_req_skill_probabilityandstatistics_randomprocess_medium-low", "d_req_skill_probabilityandstatistics_randomprocess_medium", "d_req_skill_probabilityandstatistics_randomprocess_medium-high", "d_req_skill_probabilityandstatistics_randomprocess_high",
        "d_req_skill_probabilityandstatistics_mathematicalstatistics_absent", "d_req_skill_probabilityandstatistics_mathematicalstatistics_low", "d_req_skill_probabilityandstatistics_mathematicalstatistics_medium-low", "d_req_skill_probabilityandstatistics_mathematicalstatistics_medium", "d_req_skill_probabilityandstatistics_mathematicalstatistics_medium-high", "d_req_skill_probabilityandstatistics_mathematicalstatistics_high",
        "d_req_skill_probabilityandstatistics_multivariatestatistics_absent", "d_req_skill_probabilityandstatistics_multivariatestatistics_low", "d_req_skill_probabilityandstatistics_multivariatestatistics_medium-low", "d_req_skill_probabilityandstatistics_multivariatestatistics_medium", "d_req_skill_probabilityandstatistics_multivariatestatistics_medium-high", "d_req_skill_probabilityandstatistics_multivariatestatistics_high",
        "d_req_skill_probabilityandstatistics_dataanalysis_absent", "d_req_skill_probabilityandstatistics_dataanalysis_low", "d_req_skill_probabilityandstatistics_dataanalysis_medium-low", "d_req_skill_probabilityandstatistics_dataanalysis_medium", "d_req_skill_probabilityandstatistics_dataanalysis_medium-high", "d_req_skill_probabilityandstatistics_dataanalysis_high",
        "d_req_skill_probabilityandstatistics_quantumstatistics_absent", "d_req_skill_probabilityandstatistics_quantumstatistics_low", "d_req_skill_probabilityandstatistics_quantumstatistics_medium-low", "d_req_skill_probabilityandstatistics_quantumstatistics_medium", "d_req_skill_probabilityandstatistics_quantumstatistics_medium-high", "d_req_skill_probabilityandstatistics_quantumstatistics_high",
        "d_req_skill_probabilityandstatistics_appliedfield_absent", "d_req_skill_probabilityandstatistics_appliedfield_low", "d_req_skill_probabilityandstatistics_appliedfield_medium-low", "d_req_skill_probabilityandstatistics_appliedfield_medium", "d_req_skill_probabilityandstatistics_appliedfield_medium-high", "d_req_skill_probabilityandstatistics_appliedfield_high");

		
		//Array dei termini che sostituiscono ("&<br>&nbsp&nbsp&nbsp&nbsp&nbsp", &nbsp aggiunge uno spazio bianco)
		    $substitutes = array("Age", "Category", "Difficulty", "Format", "Language", "Resource Type", "Status", "Time",
        "<b>Acquired Skills</b> (course level): Probability =", "<b>Acquired Skills</b> (course level): Statistics =", "<b>Acquired Skills</b> (course level): Regression =", "<b>Acquired Skills</b> (course level): Computational Statistics =", "<b>Acquired Skills</b> (course level): Random Process =", "<b>Acquired Skills</b> (course level): Mathematical Statistics =", "<b>Acquired Skills</b> (course level): Multivariate Statistics =", "<b>Acquired Skills</b> (course level): Data Analysis =", "<b>Acquired Skills</b> (course level): Quantum Statistics =", "<b>Acquired Skills</b> (course level): Applied Field =",
        "<b>Required Skills</b> (course level): Probability =", "<b>Required Skills</b> (course level): Statistics =", "<b>Required Skills</b> (course level): Regression =", "<b>Required Skills</b> (course level): Computational Statistics =", "<b>Required Skills</b> (course level): Random Process =", "<b>Required Skills</b> (course level): Mathematical Statistics =", "<b>Required Skills</b> (course level): Multivariate Statistics =", "<b>Required Skills</b> (course level): Data Analysis =", "<b>Required Skills</b> (course level): Quantum Statistics =", "<b>Required Skills</b> (course level): Applied Field =",
        "<b>Acquired Skills</b> (module level): Probability =", "<b>Acquired Skills</b> (module level): Statistics =", "<b>Acquired Skills</b> (module level): Regression =", "<b>Acquired Skills</b> (module level): Computational Statistics =", "<b>Acquired Skills</b> (module level): Random Process =", "<b>Acquired Skills</b> (module level): Mathematical Statistics =", "<b>Acquired Skills</b> (module level): Multivariate Statistics =", "<b>Acquired Skills</b> (module level): Data Analysis =", "<b>Acquired Skills</b> (module level): Quantum Statistics =", "<b>Acquired Skills</b> (module level): Applied Field =",
        "<b>Required Skills</b> (module level): Probability =", "<b>Required Skills</b> (module level): Statistics =", "<b>Required Skills</b> (module level): Regression =", "<b>Required Skills</b> (module level): Computational Statistics =", "<b>Required Skills</b> (module level): Random Process =", "<b>Required Skills</b> (module level): Mathematical Statistics =", "<b>Required Skills</b> (module level): Multivariate Statistics =", "<b>Required Skills</b> (module level): Data Analysis =", "<b>Required Skills</b> (module level): Quantum Statistics =", "<b>Required Skills</b> (module level): Applied Field =",
        "Young", "Teenager", "Mature", "University", "Phd", "Adult", "Young-Teenager", "Young-Mature", "Young-University", "Young-Phd", "Young-Adult", "Teenager-Mature", "Teenager-University", "Teenager-Phd", "Teenager-Adult", "Mature-University", "Mature-Phd", "Mature-Adult", "University-Phd", "University-Adult", "Phd-Adult",
        "Probability and Statistics",
        "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
        "English", "Italian", "Bulgarian", "Turkish",
        "Exercise", "Simulation", "Questionnaire", "Diagram", "Figure", "Graph", "Index", "Slide", "Table", "Narrative Text", "Exam", "Experiment", "Problem Statement", "Self Assessment", "Lecture",
        "White", "Green", "Yellow", "Red", "Black", "Gold",
        "30 Minutes", "60 Minutes", "90 Minutes", "+120 Minutes",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High",
        "Absent", "Low", "Medium-Low", "Medium", "Medium-High", "High");
		
		/*$current_lang = current_language();
		switch ($current_lang) {
    		case "en":
    			//Array termini sostituti inglesi
    			$substitutes = array("<br>&nbsp&nbsp&nbsp&nbsp&nbsp", "Age =", "Category =", "Difficulty =","Format =", "Language =", "Resource Type =","Status =", "Time =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (course level) =", "Communication Skills, Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Data Management - <b>Required Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (module level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (module level) =", "Communication Skills, Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Data Management - <b>Required Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (module level) =",
						   "Young","Teenager","Mature","University","Phd","Adult","Young-Teenager","Young-Mature","Young-University","Young-Phd","Young-Adult","Teenager-Mature","Teenager-University","Teenager-Phd","Teenager-Adult","Mature-University","Mature-Phd","Mature-Adult","University-Phd","University-Adult","Phd-Adult",
						   "Communication Skills",
						   "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
						   "English", "Italian", "Bulgarian", "Turkish",
						   "Exercise","Simulation","Questionnaire","Diagram","Figure","Graph","Index","Slide","Table","Narrative Text","Exam","Experiment","Problem Statement","Self Assessment","Lecture",
						   "White","Green","Yellow","Red","Black","Gold",
						   "30 Minutes","60 Minutes","90 Minutes","+120 Minutes",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High");
        		break;
    		case "it":
    			//Array termini sostituti italiani
        		$substitutes = array("<br>&nbsp&nbsp&nbsp&nbsp&nbsp", "Age =", "Category =", "Difficulty =","Format =", "Language =", "Resource Type =","Status =", "Time =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (course level) =", "Communication Skills, Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Data Management - <b>Required Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (module level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (module level) =", "Communication Skills, Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Data Management - <b>Required Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (module level) =",
						   "Young","Teenager","Mature","University","Phd","Adult","Young-Teenager","Young-Mature","Young-University","Young-Phd","Young-Adult","Teenager-Mature","Teenager-University","Teenager-Phd","Teenager-Adult","Mature-University","Mature-Phd","Mature-Adult","University-Phd","University-Adult","Phd-Adult",
						   "Communication Skills",
						   "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
						   "English", "Italian", "Bulgarian", "Turkish",
						   "Exercise","Simulation","Questionnaire","Diagram","Figure","Graph","Index","Slide","Table","Narrative Text","Exam","Experiment","Problem Statement","Self Assessment","Lecture",
						   "White","Green","Yellow","Red","Black","Gold",
						   "30 Minutes","60 Minutes","90 Minutes","+120 Minutes",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High");
        		break;
    		case "tr":
    			//Array termini sostituti turchi
        		$substitutes = array("<br>&nbsp&nbsp&nbsp&nbsp&nbsp", "Age =", "Category =", "Difficulty =","Format =", "Language =", "Resource Type =","Status =", "Time =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (course level) =", "Communication Skills, Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Data Management - <b>Required Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (module level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (module level) =", "Communication Skills, Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Data Management - <b>Required Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (module level) =",
						   "Young","Teenager","Mature","University","Phd","Adult","Young-Teenager","Young-Mature","Young-University","Young-Phd","Young-Adult","Teenager-Mature","Teenager-University","Teenager-Phd","Teenager-Adult","Mature-University","Mature-Phd","Mature-Adult","University-Phd","University-Adult","Phd-Adult",
						   "Communication Skills",
						   "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
						   "English", "Italian", "Bulgarian", "Turkish",
						   "Exercise","Simulation","Questionnaire","Diagram","Figure","Graph","Index","Slide","Table","Narrative Text","Exam","Experiment","Problem Statement","Self Assessment","Lecture",
						   "White","Green","Yellow","Red","Black","Gold",
						   "30 Minutes","60 Minutes","90 Minutes","+120 Minutes",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High");
        		break;
        	case "bg":
        		//Array termini sostituti bulgari
        		$substitutes = array("<br>&nbsp&nbsp&nbsp&nbsp&nbsp", "Age =", "Category =", "Difficulty =","Format =", "Language =", "Resource Type =","Status =", "Time =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (course level) =", "Communication Skills, Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Data Management - <b>Required Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (module level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (module level) =", "Communication Skills, Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Data Management - <b>Required Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (module level) =",
						   "Young","Teenager","Mature","University","Phd","Adult","Young-Teenager","Young-Mature","Young-University","Young-Phd","Young-Adult","Teenager-Mature","Teenager-University","Teenager-Phd","Teenager-Adult","Mature-University","Mature-Phd","Mature-Adult","University-Phd","University-Adult","Phd-Adult",
						   "Communication Skills",
						   "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
						   "English", "Italian", "Bulgarian", "Turkish",
						   "Exercise","Simulation","Questionnaire","Diagram","Figure","Graph","Index","Slide","Table","Narrative Text","Exam","Experiment","Problem Statement","Self Assessment","Lecture",
						   "White","Green","Yellow","Red","Black","Gold",
						   "30 Minutes","60 Minutes","90 Minutes","+120 Minutes",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High");
        		break;
        	default:
        		//Array termini sostituti inglesi
       			$substitutes = array("<br>&nbsp&nbsp&nbsp&nbsp&nbsp", "Age =", "Category =", "Difficulty =","Format =", "Language =", "Resource Type =","Status =", "Time =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (course level) =", "Communication Skills, Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Data Management - <b>Required Skills</b> (course level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (course level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (course level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (course level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (course level) =",
						   "Communication Skills, Communications Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Data Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Acquired Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Acquired Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Acquired Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Acquired Skills</b> (module level) =",
						   "Communication Skills, Communications Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Communication Ethics - <b>Required Skills</b> (module level) =", "Communication Skills, Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Data Management - <b>Required Skills</b> (module level) =", "Communication Skills, Information Technology Basics - <b>Required Skills</b> (module level) =", "Communication Skills, Product and Service Marketing - <b>Required Skills</b> (module level) =","Communication Skills, Marketing Information Management - <b>Required Skills</b> (module level) =", "Communication Skills, Strategic Marketing Planning - <b>Required Skills</b> (module level) =",
						   "Young","Teenager","Mature","University","Phd","Adult","Young-Teenager","Young-Mature","Young-University","Young-Phd","Young-Adult","Teenager-Mature","Teenager-University","Teenager-Phd","Teenager-Adult","Mature-University","Mature-Phd","Mature-Adult","University-Phd","University-Adult","Phd-Adult",
						   "Communication Skills",
						   "Very Easy", "Easy", "Medium", "Difficult", "Very Difficult",
						   "English", "Italian", "Bulgarian", "Turkish",
						   "Exercise","Simulation","Questionnaire","Diagram","Figure","Graph","Index","Slide","Table","Narrative Text","Exam","Experiment","Problem Statement","Self Assessment","Lecture",
						   "White","Green","Yellow","Red","Black","Gold",
						   "30 Minutes","60 Minutes","90 Minutes","+120 Minutes",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High",
						   "Absent","Low","Medium-Low","Medium","Medium-High","High");
		}*/
		
		$newphrase = str_replace($toReplace, $substitutes, $phrase);
		$newphrase1 = str_replace("Communication Skills, ", "", $newphrase);
		return $newphrase1;
 	}
?>
